---
# yamllint disable rule:truthy

name: Molecule

on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches:
      - master

jobs:
  ansible_build:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone repo postgresql_cluster
        uses: actions/checkout@v2

      - name: Lint playbook with Ansible v2.10
        uses: ansible/ansible-lint-action@master
        with:
          targets: |
            deploy_pgcluster.yml
            add_pgnode.yml
            add_balancer.yml
          override-deps: ansible~=2.10.0
          args: "-x 106,208,403"
  yaml_build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Run yamllint'
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_file_or_dir: '.'
          yamllint_strict: true
          yamllint_comment: true
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  test:
    needs:
      - yaml_build
      - ansible_build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro:
          - ubuntu2004
          - ubuntu1804

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip3 install molecule[docker] ansible~=2.9.0 pytest pytest-testinfra

      - name: Run Molecule tests
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}


...
